session_name: zea-template-svelte
suppress_history: false
windows:
  - layout: main-vertical
    panes:
      - yarn run start
      - ${EDITOR} -S
  - panes:
      - shell_command:
          - git fetch
          - git status
