steps:
  - name: 'node:16'
    entrypoint: yarn
    args: [install, '--frozen-lockfile']
  - name: node:16
    entrypoint: yarn
    args: [run, build]
  - name: gcr.io/cloud-builders/gsutil
    args: [-m, rsync, -d, -c, -r, dist/, 'gs://$_WEB_APP_SUBDOMAIN.zea.live']
